const $=(id)=>document.getElementById(id);
const state={plants:[],plant:null,forecast:null,history:[],metrics:null,patterns:null};
const fmt=(n,d=1)=>Number(n||0).toLocaleString('pt-BR',{maximumFractionDigits:d});
const money=(n)=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
async function api(path,opts){const r=await fetch(path,opts);if(!r.ok)throw new Error(await r.text());return r.json()}
function svgLine(target,series){const el=$(target);if(!el||!series.length)return;const W=900,H=280,p=34;const xs=series.map((_,i)=>p+i*(W-2*p)/Math.max(1,series.length-1));const vals=series.flatMap(s=>[s.a,s.b??s.a]).filter(Number.isFinite);const min=Math.min(...vals),max=Math.max(...vals),span=Math.max(1,max-min);const y=v=>H-p-(v-min)*(H-2*p)/span;let grid='';for(let i=0;i<5;i++){let yy=p+i*(H-2*p)/4;grid+=`<line class="gridline" x1="${p}" y1="${yy}" x2="${W-p}" y2="${yy}"/>`}const pathA=series.map((s,i)=>`${i?'L':'M'}${xs[i].toFixed(1)},${y(s.a).toFixed(1)}`).join(' ');const pathB=series.some(s=>Number.isFinite(s.b))?series.map((s,i)=>`${i?'L':'M'}${xs[i].toFixed(1)},${y(s.b).toFixed(1)}`).join(' '):'';el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${grid}<path class="line-a" d="${pathA}"/>${pathB?`<path class="line-b" d="${pathB}"/>`:''}</svg>`}
function svgBars(target,series){const el=$(target);if(!el||!series.length)return;const W=900,H=280,p=34;const max=Math.max(...series.map(s=>s.v),1);const bw=(W-2*p)/series.length;let bars='',labels='';series.forEach((s,i)=>{const h=(H-2*p)*s.v/max,x=p+i*bw+2,y=H-p-h;bars+=`<rect class="bar" x="${x}" y="${y}" width="${Math.max(2,bw-5)}" height="${h}" rx="2"/>`;if(i%3===0)labels+=`<text class="axis-label" x="${x}" y="${H-10}">${s.label}</text>`});el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${bars}${labels}</svg>`}
async function loadBase(){const [plants,overview,metrics,patterns]=await Promise.all([api('/api/v1/plants'),api('/api/v1/overview'),api('/api/v1/model/metrics'),api('/api/v1/analytics/patterns')]);state.plants=plants;state.metrics=metrics;state.patterns=patterns;$('plantSelect').innerHTML=plants.map(p=>`<option value="${p.code}">${p.name} • ${p.source.toUpperCase()} • ${p.region}</option>`).join('');$('eventRate').textContent=fmt(overview.event_rate_pct)+'%';$('totalCurtailed').textContent=fmt(overview.curtailed_mwh,0)+' MWh';$('plantCount').textContent=overview.plants;$('modelVersion').textContent=metrics.model_version;renderPatterns();renderMetrics();await loadPlant(plants[0].code);}
async function loadPlant(code){const [forecast,history]=await Promise.all([api(`/api/v1/plants/${code}/forecast`),api(`/api/v1/plants/${code}/history?limit=168`)]);state.forecast=forecast;state.history=history.points;const p=Math.round(forecast.risk_probability*100);$('riskValue').textContent=p+'%';$('ringText').textContent=p+'%';$('riskRing').style.setProperty('--p',`${p*3.6}deg`);$('riskLevel').textContent=forecast.risk_level;$('riskSubtitle').textContent=`Threshold de decisão: ${Math.round(forecast.decision_threshold*100)}% • ${forecast.data_mode}`;$('energyRisk').textContent=fmt(forecast.predicted_curtailed_mwh)+' MWh';$('thresholdValue').textContent=Math.round(forecast.decision_threshold*100)+'%';$('predictionNarrative').textContent=`O modelo estima ${p}% de risco e ${fmt(forecast.predicted_curtailed_mwh)} MWh esperados para o cenário atual.`;renderExplanation();renderHistory();}
function renderExplanation(){const items=state.forecast?.explanation||[];const max=Math.max(...items.map(x=>Math.abs(x.effect)),.01);$('explanationList').innerHTML=items.map(x=>`<div class="explain-row"><div class="explain-top"><span>${x.label}</span><span>${x.effect>=0?'+':''}${(x.effect*100).toFixed(1)} p.p.</span></div><div class="explain-track"><div class="explain-fill" style="width:${Math.max(4,Math.abs(x.effect)/max*100)}%"></div></div></div>`).join('')}
function renderHistory(){const s=state.history.slice(-72).map(x=>({a:x.available_generation_mw,b:x.actual_generation_mw}));svgLine('generationChart',s);const r=state.history.slice(-72).map(x=>({a:x.network_stress_index*100,b:x.curtailment_event?100:0}));svgLine('riskChart',r)}
function renderPatterns(){svgBars('hourlyChart',state.patterns.hourly.map(x=>({label:String(x.hour).padStart(2,'0')+'h',v:x.event_rate_pct})));$('reasonList').innerHTML=state.patterns.reasons.sort((a,b)=>b.mwh-a.mwh).map(x=>`<div class="reason-row"><span>${x.restriction_reason.replaceAll('_',' ')}</span><strong>${fmt(x.mwh,0)} MWh</strong></div>`).join('')}
function renderMetrics(){const c=state.metrics.classifier,r=state.metrics.regressor;const items=[['PR-AUC',c.pr_auc],['ROC-AUC',c.roc_auc],['Recall',c.recall],['F1',c.f1],['MAE energia',r.mae_mwh+' MWh'],['Threshold',state.metrics.decision_threshold]];$('modelMetrics').innerHTML=items.map(([k,v])=>`<article class="metric"><span>${k}</span><strong>${typeof v==='number'?v.toFixed(3):v}</strong><small>demo validation</small></article>`).join('')}
async function optimize(){const profile=$('profileInput').value.split(',').map(v=>Number(v.trim())).filter(v=>Number.isFinite(v)&&v>=0);if(!profile.length){$('optMessage').textContent='Informe ao menos um valor de energia.';return}const payload={plant_code:$('plantSelect').value,curtailed_profile_mwh:profile,battery_capacity_mwh:+$('batteryCap').value,battery_initial_soc_mwh:+$('batterySoc').value,battery_max_charge_mw:+$('batteryPower').value,battery_roundtrip_efficiency:.90,flexible_load_capacity_mw:+$('flexPower').value,flexible_load_total_mwh:+$('flexTotal').value,energy_value_brl_mwh:220,grid_factor_tco2_mwh:.08};$('optMessage').textContent='Otimizando...';try{const out=await api('/api/v1/optimize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('recoveryPct').textContent=fmt(out.recovery_rate_pct)+'%';$('recoveredMwh').textContent=fmt(out.recovered_mwh)+' MWh';$('lostMwh').textContent=fmt(out.lost_mwh)+' MWh';$('valuePreserved').textContent=money(out.estimated_value_preserved_brl);$('optMessage').textContent='Cenário salvo no histórico.';svgBars('dispatchChart',out.dispatch.map(x=>({label:'H'+x.hour,v:x.recovered_mwh})));}catch(e){$('optMessage').textContent='Erro: '+e.message}}
document.querySelectorAll('.nav').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(`view-${btn.dataset.view}`).classList.add('active')}));$('plantSelect').addEventListener('change',e=>loadPlant(e.target.value));$('refreshForecast').addEventListener('click',()=>loadPlant($('plantSelect').value));$('runOptimization').addEventListener('click',optimize);loadBase().then(optimize).catch(e=>{console.error(e);document.body.insertAdjacentHTML('beforeend',`<div style="position:fixed;bottom:20px;right:20px;background:#54201d;padding:12px;border-radius:10px">Falha ao iniciar: ${e.message}</div>`)});
